calendarBoxFriend:
  caption:
    ja_JP: "カレンダー（フレンド用）"
  description:
    ja_JP: "カレンダー（フレンド用）を表示します"
  component: [gacalendar, calendarBoxFriend]
  config:
    domain:
      Name:       "domain"
      Caption:    "GoogleAppsDomain"
      FormType:   "input"
      ValueType:  "text"
      IsRequired: true
